language: ruby
rvm:
  - 2.5.7
  - 2.6.5
notifications:
  slack:
    secure: rj7jpV3x6AU90/+QAyGu60qGpQBU45rE/VacQqTDgvZxCr1oAP3CdoFmKrRaYX+pmkU6nPm5Oup1icLKD5WtMjPFTfvUJW1qfVswhGYWzH45+3t6FUzGJu3ArISs8pywuITgYEWD5+aKnLec6p7SCibcMfantCVP8eqNd9pXFwdoDjdqXHwQt5oISFP9l6PeeuL66MzdHEeQX+Ap/34Z6y5aI/E6zlRgmvmtVlI8HtqZWWkQcnddNQbBVZGD8qJ7DfIu5afs+r/LOqSCdZImYrDDIwsVI1+EWCK1E4bAjpjsX5vLjs7XzY+TGxQAWp7XLAluQ1jtm/Fae9icKW/NiiS5NoaGUPf4/J2JCPsn7WGMsCBIqR7hyQgHgAF11MW8xVy9RT5O47C278EiKOtD5WjZKK1yMj+ZRJ67qp1QZosXrmUZRN4CfVTdLVcSTjgOnRo/8jvJ5V5lEvj761Pz5zaaTMfjf/ycMqN2hsEPDP82oChGkCCeoD4b2GDCSBkWOAGVG8836EUbvPZ263ymp4Ir8K8eoKkgvlLr1mozKEHJNFTc3YOX/KqiJ0o+Zq2orHqF1J86VYiD/RaZSAf242OTWijG9Wb3yVjtZAwdDzilp01n1+IQfBwOflxTXkscHf1/KzwMtEU7qPyNcNEk1lJCxysR1I4rbP7NIzNSDZs=
